 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/journal_entries", type: :request do
  
  # JournalEntry. As you add validations to JournalEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      JournalEntry.create! valid_attributes
      get journal_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      journal_entry = JournalEntry.create! valid_attributes
      get journal_entry_url(journal_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_journal_entry_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      journal_entry = JournalEntry.create! valid_attributes
      get edit_journal_entry_url(journal_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new JournalEntry" do
        expect {
          post journal_entries_url, params: { journal_entry: valid_attributes }
        }.to change(JournalEntry, :count).by(1)
      end

      it "redirects to the created journal_entry" do
        post journal_entries_url, params: { journal_entry: valid_attributes }
        expect(response).to redirect_to(journal_entry_url(JournalEntry.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new JournalEntry" do
        expect {
          post journal_entries_url, params: { journal_entry: invalid_attributes }
        }.to change(JournalEntry, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post journal_entries_url, params: { journal_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        patch journal_entry_url(journal_entry), params: { journal_entry: new_attributes }
        journal_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the journal_entry" do
        journal_entry = JournalEntry.create! valid_attributes
        patch journal_entry_url(journal_entry), params: { journal_entry: new_attributes }
        journal_entry.reload
        expect(response).to redirect_to(journal_entry_url(journal_entry))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        journal_entry = JournalEntry.create! valid_attributes
        patch journal_entry_url(journal_entry), params: { journal_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested journal_entry" do
      journal_entry = JournalEntry.create! valid_attributes
      expect {
        delete journal_entry_url(journal_entry)
      }.to change(JournalEntry, :count).by(-1)
    end

    it "redirects to the journal_entries list" do
      journal_entry = JournalEntry.create! valid_attributes
      delete journal_entry_url(journal_entry)
      expect(response).to redirect_to(journal_entries_url)
    end
  end
end
